id: swagger-ui

info:
  name: Swagger UI
  author: vidocsecurity,Arqsz
  severity: low
  description: Swagger UI exposes information about endpoints and sometimes it is vulnerable tu XSS
  tags: swagger-ui,services,exposure

requests:
  - method: "GET"
    path:
      # - '{{BaseURL}}/'
      - "{{BaseURL}}/index.html"
      - "{{BaseURL}}/swagger-ui"
      - "{{BaseURL}}/api/"
      - "{{BaseURL}}/docs/"
      - "{{BaseURL}}/idm/v2/api-docs"
      - "{{BaseURL}}/docs/api-reference"
      - "{{BaseURL}}/swaggerui"
      - "{{BaseURL}}/api/help"
      - "{{BaseURL}}/doc"
      - "{{BaseURL}}/api-reference"
      - "{{BaseURL}}/swagger/docs/v1"
      - "{{BaseURL}}/reference"
      - "{{BaseURL}}/swagger/ui/index"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api-docs/"
      - "{{BaseURL}}/api/index.html"
      - "{{BaseURL}}/api/docs/"
      - "{{BaseURL}}/api/swagger/index.html"
      - "{{BaseURL}}/api/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui/api-docs"
      - "{{BaseURL}}/api/api-docs"
      - "{{BaseURL}}/api/apidocs"
      - "{{BaseURL}}/api/swagger"
      - "{{BaseURL}}/api/swagger/static/index.html"
      - "{{BaseURL}}/api/swagger-resources"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/__swagger__/"
      - "{{BaseURL}}/api/_swagger_/"
      - "{{BaseURL}}/api/spec"
      - "{{BaseURL}}/api/swagger/ui/index"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/api/v2/doc"
      - "{{BaseURL}}/api/v1/"
      - "{{BaseURL}}/api/v1/doc"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/classicapi/doc/"
      - "{{BaseURL}}/api/v1/openapi"
      - "{{BaseURL}}/openapi.json"
      - "{{BaseURL}}/openapi.yml"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/swagger/openapi.json"
      - "{{BaseURL}}/swagger/openapi.yml"
      - "{{BaseURL}}/swagger/swagger.json"

    stop-at-first-match: true
    redirects: true
    max-redirects: 3
    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - "Swagger UI"
          - "openapi"
          - "swagger"

      - type: status
        status:
          - 200
